/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrophiesRouteImport } from './routes/trophies'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PassRouteImport } from './routes/pass'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as EventRouteImport } from './routes/event'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CplayRouteImport } from './routes/cplay'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyCodeRouteImport } from './routes/party.$code'

const TrophiesRoute = TrophiesRouteImport.update({
  id: '/trophies',
  path: '/trophies',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CplayRoute = CplayRouteImport.update({
  id: '/cplay',
  path: '/cplay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyCodeRoute = PartyCodeRouteImport.update({
  id: '/party/$code',
  path: '/party/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cplay': typeof CplayRoute
  '/create': typeof CreateRoute
  '/customize': typeof CustomizeRoute
  '/event': typeof EventRoute
  '/friends': typeof FriendsRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/online': typeof OnlineRoute
  '/pass': typeof PassRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/stats': typeof StatsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/trophies': typeof TrophiesRoute
  '/party/$code': typeof PartyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cplay': typeof CplayRoute
  '/create': typeof CreateRoute
  '/customize': typeof CustomizeRoute
  '/event': typeof EventRoute
  '/friends': typeof FriendsRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/online': typeof OnlineRoute
  '/pass': typeof PassRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/stats': typeof StatsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/trophies': typeof TrophiesRoute
  '/party/$code': typeof PartyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cplay': typeof CplayRoute
  '/create': typeof CreateRoute
  '/customize': typeof CustomizeRoute
  '/event': typeof EventRoute
  '/friends': typeof FriendsRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/online': typeof OnlineRoute
  '/pass': typeof PassRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/stats': typeof StatsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/trophies': typeof TrophiesRoute
  '/party/$code': typeof PartyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cplay'
    | '/create'
    | '/customize'
    | '/event'
    | '/friends'
    | '/levels'
    | '/multiplayer'
    | '/online'
    | '/pass'
    | '/play'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/stats'
    | '/tasks'
    | '/team'
    | '/trophies'
    | '/party/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cplay'
    | '/create'
    | '/customize'
    | '/event'
    | '/friends'
    | '/levels'
    | '/multiplayer'
    | '/online'
    | '/pass'
    | '/play'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/stats'
    | '/tasks'
    | '/team'
    | '/trophies'
    | '/party/$code'
  id:
    | '__root__'
    | '/'
    | '/cplay'
    | '/create'
    | '/customize'
    | '/event'
    | '/friends'
    | '/levels'
    | '/multiplayer'
    | '/online'
    | '/pass'
    | '/play'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/stats'
    | '/tasks'
    | '/team'
    | '/trophies'
    | '/party/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CplayRoute: typeof CplayRoute
  CreateRoute: typeof CreateRoute
  CustomizeRoute: typeof CustomizeRoute
  EventRoute: typeof EventRoute
  FriendsRoute: typeof FriendsRoute
  LevelsRoute: typeof LevelsRoute
  MultiplayerRoute: typeof MultiplayerRoute
  OnlineRoute: typeof OnlineRoute
  PassRoute: typeof PassRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  StatsRoute: typeof StatsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  TrophiesRoute: typeof TrophiesRoute
  PartyCodeRoute: typeof PartyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trophies': {
      id: '/trophies'
      path: '/trophies'
      fullPath: '/trophies'
      preLoaderRoute: typeof TrophiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cplay': {
      id: '/cplay'
      path: '/cplay'
      fullPath: '/cplay'
      preLoaderRoute: typeof CplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$code': {
      id: '/party/$code'
      path: '/party/$code'
      fullPath: '/party/$code'
      preLoaderRoute: typeof PartyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CplayRoute: CplayRoute,
  CreateRoute: CreateRoute,
  CustomizeRoute: CustomizeRoute,
  EventRoute: EventRoute,
  FriendsRoute: FriendsRoute,
  LevelsRoute: LevelsRoute,
  MultiplayerRoute: MultiplayerRoute,
  OnlineRoute: OnlineRoute,
  PassRoute: PassRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  StatsRoute: StatsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  TrophiesRoute: TrophiesRoute,
  PartyCodeRoute: PartyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
